name: Automatically update from upstream
on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  merge-upstream-master:
    runs-on: ubuntu-latest
    container: alpine

    steps:
      - name: Install tools
        run: apk add --no-cache coreutils git tar zstd curl jq

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Merge Upstream
        run: |
          git remote add --tags -f upstream "https://github.com/aristocratos/btop.git"
          git checkout main
          git merge --ff-only upstream/main
          git push
          git checkout cmake
          LAST_NEW_TAG=$(git tag --list --sort=taggerdate --no-merged | tail -n1)
          [ ! -z "$LAST_NEW_TAG" ] && git merge --no-edit refs/tags/$LAST_NEW_TAG && git push
