name: Automatically update from upstream
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  merge-upstream-master:
    runs-on: ubuntu-latest
    container: alpine

    steps:
      - name: Install tools
        run: apk add --no-cache coreutils git tar zstd curl jq

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Merge Upstream
        run: |
          git remote add --tags -f upstream "https://github.com/aristocratos/btop.git"
          git checkout main
          LAST_NEW_TAG=$(git --no-pager tag --list --sort=taggerdate --no-merged | tail -n1)
          if [ ! -z "$LAST_NEW_TAG" ]
          then
            if (git --no-pager diff --name-only origin/main -- Makefile | grep Makefile > /dev/null)
            then
              echo upstream Makefile changed
              exit 1
            fi
            git --no-pager merge --no-progress --no-edit --commit --ff refs/tags/$LAST_NEW_TAG
            git push
          fi
