name: Continuous Build MacOS

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*.*'
    paths:
      - 'src/**'
      - '!src/linux/**'
      - '!src/freebsd/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/*'

jobs:
  build-osx:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          make CXX=g++-11 ARCH=x86_64
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          mv bin/btop bin/btop-x86_64-$GIT_HASH
          ls -alh bin

      - uses: actions/upload-artifact@v2
        with:
          name: btop-x86_64-macos
          path: 'bin/*'
